server:
  port: 9887
  servlet:
    context-path: /api

spring:
  application:
    name: notify-center-backend

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notify_center
    username: root
    password: 123456

  # session 失效时间
  session:
    timeout: 1800
    store-type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 8
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value:
      logic-not-delete-value: 0
